export const GET_EVENTS_REQUEST = "event/GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "event/GET_EVENTS_SUCCESS";

export const CREATE_EVENT_REQUEST = "event/CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "event/CREATE_EVENT_SUCCESS";

export const DELETE_EVENT_REQUEST = "event/DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "event/DELETE_EVENT_SUCCESS";

export const GET_BOOKINGS_REQUEST = "event/GET_BOOKINGS_REQUEST";
export const GET_BOOKINGS_SUCCESS = "event/GET_BOOKINGS_SUCCESS";

export const BOOK_EVENT_REQUEST = "event/BOOK_EVENT_REQUEST";
export const BOOK_EVENT_SUCCESS = "event/BOOK_EVENT_SUCCESS";

export const CANCEL_BOOKING_EVENT_REQUEST = "event/CANCEL_BOOKING_EVENT_REQUEST";
export const CANCEL_BOOKING_EVENT_SUCCESS = "event/CANCEL_BOOKING_EVENT_SUCCESS";